name:                luna-js
version:             "0.1"
author:              "Author name here"
maintainer:          "example@example.com"

executables:
  luna-js:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - luna-core
    - luna-parser
    - vector-text
    - vector