ghc-options:
    $locals:
        -DFastCompilation
        -fenable-rewrite-rules
        -threaded
        -funbox-strict-fields
        -O0
        -fconstraint-solver-iterations=100
    $everything:
        -fconstraint-solver-iterations=100
local-bin-path: dist/bin/public/luna
packages:
    - location: shell
    - location: core
    - location: passes
    - location: stdlib
    - location: project
    - location: syntax/text/parser
    - location: syntax/text/lexer
    - location: lib/ci
    - location: js
resolver: ./build_config/luna-snapshot.yaml
